---
- hosts: "{{ variable_host | default('BASE') }}" 
  remote_user: ansioper
  become_method: sudo

  tasks:
  - name: Check memory space 
    command: free -m 
    register: command_result

  - name: Show results
    debug: msg="{{ command_result.stdout_lines }}"
