---
- hosts: "{{ variable_host | default('BASE') }}" 
  remote_user: ansioper
  become: true
  become_method: sudo
  
  vars:
    mariadb_root_pass: any999any 
    packages:
      - mariadb
      - mariadb-server
      - mariadb-test
      - MySQL-python 
    servers_hostnames:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost

  tasks:
  - name: Install MariaDB 
    yum: 
      name="{{ item }}" 
      state=latest 
    with_items: "{{ packages }}"

  - name: Enable external connections
    lineinfile:
      dest: /etc/my.cnf.d/server.cnf
      backup: yes
      firstmatch: yes
      insertafter: '^\s*\[mysqld\]'
      line: 'bind-address = 0.0.0.0'

  - name: Enable MariaDB  service
    systemd: 
      name: mariadb
      enabled: yes

  - name: Start MariaDB  service
    systemd:
      name: mariadb
      state: started

  - name: Remove test database
    mysql_db:
      name: test
      state: absent

  - name: Remove all anonymous user
    mysql_user: 
      name: ''
      host_all: yes
      state: absent

  - name: Update MariaDB root password
    mysql_user: 
      name: root
      host_all: yes
      password: "{{ mariadb_root_pass }}"

  - name: Add firewalld rule - mariadb
    firewalld:
      port: 3306/tcp 
      permanent: true
      state: enabled

  - name: Reload firewalld service
    systemd:
      name: firewalld
      state: restarted 

