---
- hosts: "{{ variable_host | default('BASE') }}" 
  remote_user: ansioper
  become: true
  become_method: sudo
  
  vars:
    packages:
      - nginx

  tasks:
  - name: Install Nginx Packages 
    yum: 
      name="{{ item }}" 
      state=latest 
    with_items: "{{ packages }}"

  - name: Enable Nginx service
    systemd: 
      name: nginx
      enabled: yes

  - name: Start Nginx service
    systemd:
      name: nginx
      state: started

  - name: Add firewalld rule - http
    firewalld:
      service: http
      permanent: true
      state: enabled

  - name: Add firewalld rule - https
    firewalld:
      service: https
      permanent: true
      state: enabled

  - name: Reload firewalld service
    systemd:
      name: firewalld
      state: restarted 

